In [18]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
from sklearn.utils import shuffle

In [19]:
M = 2 #入力データの次元
K = 3 #クラス数
n = 100 #クラスごとのデータ数
N = n * K #全データ数

In [20]:
#サンプルデータ生成
X1 = np.random.randn(n,M) + np.array([0,10])
X2 = np.random.randn(n,M) + np.array([5,5])
X3 = np.random.randn(n,M) + np.array([10,0])
Y1 = np.array([[1,0,0] for i in range(n)])
Y2 = np.array([[0,1,0] for i in range(n)])
Y3 = np.array([[0,0,1] for i in range(n)])

X = np.concatenate((X1,X2,X3), axis=0)
Y = np.concatenate((Y1,Y2,Y3), axis=0)

In [21]:
model = Sequential()
model.add(Dense(input_dim=M, units=K))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))

In [23]:
minibatch_size = 50
model.fit(X, Y, epochs=20, batch_size=minibatch_size)

Epoch 1/20
300/300 [==============================] - 2s - loss: 1.7332      
Epoch 2/20
300/300 [==============================] - 0s - loss: 0.2276     
Epoch 3/20
300/300 [==============================] - 0s - loss: 0.1536     
Epoch 4/20
300/300 [==============================] - 0s - loss: 0.1153     
Epoch 5/20
300/300 [==============================] - 0s - loss: 0.0939     
Epoch 6/20
300/300 [==============================] - 0s - loss: 0.0800     
Epoch 7/20
300/300 [==============================] - 0s - loss: 0.0695     
Epoch 8/20
300/300 [==============================] - 0s - loss: 0.0619     
Epoch 9/20
300/300 [==============================] - 0s - loss: 0.0563     
Epoch 10/20
300/300 [==============================] - 0s - loss: 0.0513     
Epoch 11/20
300/300 [==============================] - 0s - loss: 0.0469     
Epoch 12/20
300/300 [==============================] - 0s - loss: 0.0437     
Epoch 13/20
300/300 [==============================] - 0s - loss: 0.0408

In [25]:
X_,Y_ = shuffle(X, Y)
classes = model.predict_classes(X_[0:10], batch_size=1 )
prob = model.predict_proba(X_[0:10], batch_size=1 )

 1/10 [==>...........................] - ETA: 0s

In [27]:
print('classified:')
print(np.argmax(model.predict(X_[0:10]), axis=1) == classes)
print()
print('output probability:')
print(prob)

classified:
[ True  True  True  True  True  True  True  True  True  True]

output probability:
[[  1.80859736e-03   9.79868352e-01   1.83230918e-02]
 [  5.56386084e-08   2.43424959e-02   9.75657463e-01]
 [  1.71913950e-08   2.10387614e-02   9.78961229e-01]
 [  1.00903064e-02   9.81853545e-01   8.05616006e-03]
 [  2.93358262e-08   8.10238253e-03   9.91897583e-01]
 [  9.97552574e-01   2.44745938e-03   1.97867528e-10]
 [  3.20919575e-08   1.18640885e-02   9.88135934e-01]
 [  9.37741280e-01   6.22584112e-02   1.96469941e-07]
 [  9.95844543e-01   4.15548822e-03   2.66670952e-09]
 [  9.86437261e-01   1.35627603e-02   1.83588309e-08]]
